name: Nuxt upgrade

on:
  workflow_dispatch:
  schedule:
  - cron: '* 8 * * 1'

permissions:
  contents: read
  id-token: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: pnpm

    - name: Upgrade
      run: npx nuxt upgrade --force
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: 'ci/Weekly nuxt upgrade'
        commit-message: 'ci: nuxt upgrade'
        branch: 'ci/nuxt-upgrade'
